#!/bin/bash
#
# Downloads the Mozilla CA certificate bundle from curl.se and converts it
# to a C source file with a const char array for embedding in the binary.
# The declarations live in src/cacert.h (hand-written).
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$PROJECT_DIR/src/cacert.c"

URL="https://curl.se/ca/cacert.pem"

echo "Downloading CA bundle from $URL ..."
PEM=$(curl -fsSL "$URL")

echo "Generating $OUTPUT ..."

cat > "$OUTPUT" <<'HEADER'
/* clang-format off */

/*
 * Mozilla CA certificate bundle.
 * Generated by scripts/update-ca-bundle.sh — do not edit manually.
 * Source: https://curl.se/ca/cacert.pem
 */

#include "cacert.h"

const char tjs_cacert_pem[] =
HEADER

# Convert PEM to C string literal (each line becomes "line\n")
echo "$PEM" | while IFS= read -r line; do
    # Escape backslashes and double quotes
    escaped=$(printf '%s' "$line" | sed 's/\\/\\\\/g; s/"/\\"/g')
    printf '    "%s\\n"\n' "$escaped" >> "$OUTPUT"
done

cat >> "$OUTPUT" <<'FOOTER'
;

const size_t tjs_cacert_pem_len = sizeof(tjs_cacert_pem) - 1;
FOOTER

echo "Done. $(wc -l < "$OUTPUT" | tr -d ' ') lines written."
