import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The hand-curated `global` API groups below (Filesystem, Networking, …) stay
// manual because TypeDoc can't reproduce that functional grouping. The
// standard-library modules, however, are sourced straight from the sidebar
// TypeDoc generates, so adding a stdlib symbol never requires editing this file.
let stdlibModules: any[] = [];
try {
  const typedocSidebar = require('./docs/api/typedoc-sidebar.cjs') as Array<{ label?: string }>;
  stdlibModules = typedocSidebar.filter((c) => c.label?.startsWith('tjs:'));
} catch {
  // typedoc-sidebar.cjs is produced by `npm run generate-api`; until that runs
  // the Standard Library section is simply empty.
}

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'getting-started',
        'cli',
        'building',
        'typescript',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [
        'features/web-platform-apis',
        'features/runtime-features',
        'features/standard-library',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/modules',
        'guides/networking',
        'guides/serve',
        'guides/child-processes',
        'guides/filesystem',
        'guides/hashing',
        'guides/ffi',
        'guides/http-proxy',
        'guides/code-bundling',
        'guides/standalone-executables',
        'guides/app-packages',
      ],
    },
    'versioning',
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'GitHub',
          href: 'https://github.com/saghul/txiki.js',
        },
        {
          type: 'link',
          label: '@txikijs/types',
          href: 'https://www.npmjs.com/package/@txikijs/types',
        },
        {
          type: 'link',
          label: 'FOSDEM 2022 Talk',
          href: 'https://video.fosdem.org/2022/D.javascript/building_a_tiny_javascript_runtime_with_quickjs.mp4',
        },
      ],
    },
  ],
  apiSidebar: [
    'api-reference',
    {
      type: 'category',
      label: 'Filesystem',
      collapsed: true,
      items: [
        'api/global.tjs.Function.open',
        'api/global.tjs.Function.readFile',
        'api/global.tjs.Function.writeFile',
        'api/global.tjs.Function.readDir',
        'api/global.tjs.Function.readLink',
        'api/global.tjs.Function.stat',
        'api/global.tjs.Function.lstat',
        'api/global.tjs.Function.statFs',
        'api/global.tjs.Function.chmod',
        'api/global.tjs.Function.chown',
        'api/global.tjs.Function.lchown',
        'api/global.tjs.Function.utime',
        'api/global.tjs.Function.lutime',
        'api/global.tjs.Function.rename',
        'api/global.tjs.Function.copyFile',
        'api/global.tjs.Function.remove',
        'api/global.tjs.Function.link',
        'api/global.tjs.Function.symlink',
        'api/global.tjs.Function.realPath',
        'api/global.tjs.Function.makeDir',
        'api/global.tjs.Function.makeTempDir',
        'api/global.tjs.Function.makeTempFile',
        'api/global.tjs.Function.watch',
        'api/global.tjs.Interface.FileHandle',
        'api/global.tjs.Interface.DirHandle',
        'api/global.tjs.Interface.DirEnt',
        'api/global.tjs.Interface.StatResult',
        'api/global.tjs.Interface.StatFsResult',
        'api/global.tjs.Interface.MakeDirOptions',
        'api/global.tjs.Interface.RemoveOptions',
        'api/global.tjs.Interface.SymlinkOptions',
        'api/global.tjs.Interface.FileWatcher',
        'api/global.tjs.TypeAlias.WatchEventHandler',
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      collapsed: true,
      items: [
        'api/global.tjs.Function.connect',
        'api/global.tjs.Function.listen',
        'api/global.tjs.Function.lookup',
        'api/global.Class.TCPSocket',
        'api/global.Class.TCPServerSocket',
        'api/global.Class.TLSSocket',
        'api/global.Class.TLSServerSocket',
        'api/global.Class.UDPSocket',
        'api/global.Class.PipeSocket',
        'api/global.Class.PipeServerSocket',
        'api/global.tjs.Interface.Addr',
        'api/global.tjs.Interface.LookupOptions',
        'api/global.tjs.Interface.ConnectOptions',
        'api/global.tjs.Interface.ListenOptions',
        'api/global.tjs.Interface.TLSConnectOptions',
        'api/global.tjs.Interface.TLSListenOptions',
        'api/global.Interface.TCPSocketOpenInfo',
        'api/global.Interface.TCPSocketOptions',
        'api/global.Interface.TCPServerSocketOpenInfo',
        'api/global.Interface.TCPServerSocketOptions',
        'api/global.Interface.TLSSocketOpenInfo',
        'api/global.Interface.TLSSocketOptions',
        'api/global.Interface.TLSServerSocketOpenInfo',
        'api/global.Interface.TLSServerSocketOptions',
        'api/global.Interface.UDPSocketOpenInfo',
        'api/global.Interface.UDPSocketOptions',
        'api/global.Interface.UDPMessage',
        'api/global.Interface.MulticastController',
        'api/global.Interface.PipeSocketOpenInfo',
        'api/global.Interface.PipeServerSocketOpenInfo',
        'api/global.Interface.PipeServerSocketOptions',
        'api/global.tjs.TypeAlias.Transport',
      ],
    },
    {
      type: 'category',
      label: 'HTTP Server',
      collapsed: true,
      items: [
        'api/global.tjs.Function.serve',
        'api/global.tjs.Interface.ServeOptions',
        'api/global.tjs.Interface.TlsOptions',
        'api/global.tjs.Interface.Server',
        'api/global.tjs.Interface.RequestContext',
        'api/global.tjs.TypeAlias.FetchHandler',
        'api/global.tjs.Interface.WebSocketHandlers',
        'api/global.tjs.Interface.ServerWebSocket',
        'api/global.tjs.Interface.UpgradeOptions',
      ],
    },
    {
      type: 'category',
      label: 'Process',
      collapsed: true,
      items: [
        'api/global.tjs.Function.spawn',
        'api/global.tjs.Function.exec',
        'api/global.tjs.Function.exit',
        'api/global.tjs.Function.kill',
        'api/global.tjs.Function.addSignalListener',
        'api/global.tjs.Function.removeSignalListener',
        'api/global.tjs.Interface.Process',
        'api/global.tjs.Interface.ProcessOptions',
        'api/global.tjs.Interface.ProcessStatus',
        'api/global.tjs.Interface.ProcessReadableStream',
        'api/global.tjs.TypeAlias.ProcessStdio',
        'api/global.tjs.TypeAlias.Signal',
        'api/global.tjs.TypeAlias.SignalListener',
        'api/global.tjs.Variable.pid',
        'api/global.tjs.Variable.ppid',
      ],
    },
    {
      type: 'category',
      label: 'System',
      collapsed: true,
      items: [
        'api/global.tjs.Variable.args',
        'api/global.tjs.Variable.cwd',
        'api/global.tjs.Variable.env',
        'api/global.tjs.Variable.exePath',
        'api/global.tjs.Variable.homeDir',
        'api/global.tjs.Variable.hostName',
        'api/global.tjs.Variable.tmpDir',
        'api/global.tjs.Variable.version',
        'api/global.tjs.Variable.stdin',
        'api/global.tjs.Variable.stdout',
        'api/global.tjs.Variable.stderr',
        'api/global.tjs.Function.chdir',
        'api/global.tjs.TypeAlias.Environment',
        'api/global.tjs.TypeAlias.StdioType',
        'api/global.tjs.Interface.StdioInputStream',
        'api/global.tjs.Interface.StdioOutputStream',
        'api/global.tjs.Namespace.system',
        'api/global.tjs.system.Variable.cpus',
        'api/global.tjs.system.Variable.loadAvg',
        'api/global.tjs.system.Variable.networkInterfaces',
        'api/global.tjs.system.Variable.uptime',
        'api/global.tjs.system.Variable.userInfo',
        'api/global.tjs.system.Interface.UserInfo',
        'api/global.tjs.system.Interface.CpuInfo',
        'api/global.tjs.system.Interface.CpuTimes',
        'api/global.tjs.system.Interface.NetworkInterface',
      ],
    },
    {
      type: 'category',
      label: 'Engine',
      collapsed: true,
      items: [
        'api/global.tjs.Namespace.engine',
        'api/global.tjs.engine.Variable.compile',
        'api/global.tjs.engine.Variable.serialize',
        'api/global.tjs.engine.Variable.deserialize',
        'api/global.tjs.engine.Variable.evalBytecode',
        'api/global.tjs.engine.Variable.gc',
        'api/global.tjs.engine.Variable.versions',
        'api/global.tjs.engine.Variable.features',
        'api/global.tjs.TypeAlias.CompiledCode',
      ],
    },
    {
      type: 'category',
      label: 'Utilities',
      collapsed: true,
      items: [
        'api/global.tjs.Function.createConsole',
        'api/global.tjs.Class.Error',
        'api/global.tjs.Interface.ConsolePrinterOptions',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: true,
      items: [
        'api/global.tjs.Function.setImportMap',
        'api/global.tjs.Interface.ImportMap',
      ],
    },
    {
      type: 'category',
      label: 'Standard Library',
      collapsed: false,
      // The standard-library API sidebar is generated by TypeDoc
      // (`npm run generate-api`), so new symbols appear automatically and never
      // need to be listed here by hand.
      items: stdlibModules,
    },
  ],
};

export default sidebars;
