import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'getting-started',
        'building',
        'typescript',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [
        'features/web-platform-apis',
        'features/runtime-features',
        'features/standard-library',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/standalone-executables',
        'guides/code-bundling',
      ],
    },
    'versioning',
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'GitHub',
          href: 'https://github.com/saghul/txiki.js',
        },
        {
          type: 'link',
          label: '@txikijs/types',
          href: 'https://www.npmjs.com/package/@txikijs/types',
        },
        {
          type: 'link',
          label: 'FOSDEM 2022 Talk',
          href: 'https://video.fosdem.org/2022/D.javascript/building_a_tiny_javascript_runtime_with_quickjs.mp4',
        },
      ],
    },
  ],
  apiSidebar: [
    'api-reference',
    {
      type: 'category',
      label: 'Filesystem',
      collapsed: true,
      items: [
        'api/global.tjs.Function.open',
        'api/global.tjs.Function.readFile',
        'api/global.tjs.Function.readDir',
        'api/global.tjs.Function.readLink',
        'api/global.tjs.Function.stat',
        'api/global.tjs.Function.lstat',
        'api/global.tjs.Function.statFs',
        'api/global.tjs.Function.chmod',
        'api/global.tjs.Function.chown',
        'api/global.tjs.Function.lchown',
        'api/global.tjs.Function.utime',
        'api/global.tjs.Function.lutime',
        'api/global.tjs.Function.rename',
        'api/global.tjs.Function.copyFile',
        'api/global.tjs.Function.remove',
        'api/global.tjs.Function.link',
        'api/global.tjs.Function.symlink',
        'api/global.tjs.Function.realPath',
        'api/global.tjs.Function.makeDir',
        'api/global.tjs.Function.makeTempDir',
        'api/global.tjs.Function.makeTempFile',
        'api/global.tjs.Function.watch',
        'api/global.tjs.Interface.FileHandle',
        'api/global.tjs.Interface.DirHandle',
        'api/global.tjs.Interface.DirEnt',
        'api/global.tjs.Interface.StatResult',
        'api/global.tjs.Interface.StatFsResult',
        'api/global.tjs.Interface.MakeDirOptions',
        'api/global.tjs.Interface.RemoveOptions',
        'api/global.tjs.Interface.SymlinkOptions',
        'api/global.tjs.Interface.FileWatcher',
        'api/global.tjs.TypeAlias.WatchEventHandler',
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      collapsed: true,
      items: [
        'api/global.tjs.Function.connect',
        'api/global.tjs.Function.listen',
        'api/global.tjs.Function.lookup',
        'api/global.Class.TCPSocket',
        'api/global.Class.TCPServerSocket',
        'api/global.Class.UDPSocket',
        'api/global.Class.PipeSocket',
        'api/global.Class.PipeServerSocket',
        'api/global.tjs.Interface.Addr',
        'api/global.tjs.Interface.LookupOptions',
        'api/global.tjs.Interface.ConnectOptions',
        'api/global.tjs.Interface.ListenOptions',
        'api/global.Interface.TCPSocketOpenInfo',
        'api/global.Interface.TCPSocketOptions',
        'api/global.Interface.TCPServerSocketOpenInfo',
        'api/global.Interface.TCPServerSocketOptions',
        'api/global.Interface.UDPSocketOpenInfo',
        'api/global.Interface.UDPSocketOptions',
        'api/global.Interface.UDPMessage',
        'api/global.Interface.PipeSocketOpenInfo',
        'api/global.Interface.PipeServerSocketOpenInfo',
        'api/global.Interface.PipeServerSocketOptions',
        'api/global.tjs.TypeAlias.Transport',
      ],
    },
    {
      type: 'category',
      label: 'HTTP Server',
      collapsed: true,
      items: [
        'api/global.tjs.Function.serve',
        'api/global.tjs.Interface.ServeOptions',
        'api/global.tjs.Interface.Server',
        'api/global.tjs.Interface.RequestContext',
        'api/global.tjs.TypeAlias.FetchHandler',
        'api/global.tjs.Interface.WebSocketHandlers',
        'api/global.tjs.Interface.ServerWebSocket',
        'api/global.tjs.Interface.UpgradeOptions',
      ],
    },
    {
      type: 'category',
      label: 'Process',
      collapsed: true,
      items: [
        'api/global.tjs.Function.spawn',
        'api/global.tjs.Function.exec',
        'api/global.tjs.Function.exit',
        'api/global.tjs.Function.kill',
        'api/global.tjs.Function.addSignalListener',
        'api/global.tjs.Function.removeSignalListener',
        'api/global.tjs.Interface.Process',
        'api/global.tjs.Interface.ProcessOptions',
        'api/global.tjs.Interface.ProcessStatus',
        'api/global.tjs.Interface.ProcessReadableStream',
        'api/global.tjs.TypeAlias.ProcessStdio',
        'api/global.tjs.TypeAlias.Signal',
        'api/global.tjs.TypeAlias.SignalListener',
        'api/global.tjs.Variable.pid',
        'api/global.tjs.Variable.ppid',
      ],
    },
    {
      type: 'category',
      label: 'System',
      collapsed: true,
      items: [
        'api/global.tjs.Variable.args',
        'api/global.tjs.Variable.cwd',
        'api/global.tjs.Variable.env',
        'api/global.tjs.Variable.exePath',
        'api/global.tjs.Variable.homeDir',
        'api/global.tjs.Variable.hostName',
        'api/global.tjs.Variable.tmpDir',
        'api/global.tjs.Variable.version',
        'api/global.tjs.Variable.stdin',
        'api/global.tjs.Variable.stdout',
        'api/global.tjs.Variable.stderr',
        'api/global.tjs.Function.chdir',
        'api/global.tjs.TypeAlias.Environment',
        'api/global.tjs.TypeAlias.StdioType',
        'api/global.tjs.Interface.StdioInputStream',
        'api/global.tjs.Interface.StdioOutputStream',
        'api/global.tjs.Namespace.system',
        'api/global.tjs.system.Variable.arch',
        'api/global.tjs.system.Variable.platform',
        'api/global.tjs.system.Variable.cpus',
        'api/global.tjs.system.Variable.loadAvg',
        'api/global.tjs.system.Variable.networkInterfaces',
        'api/global.tjs.system.Variable.osRelease',
        'api/global.tjs.system.Variable.uptime',
        'api/global.tjs.system.Variable.userInfo',
        'api/global.tjs.system.Interface.UserInfo',
        'api/global.tjs.system.Interface.CpuInfo',
        'api/global.tjs.system.Interface.CpuTimes',
        'api/global.tjs.system.Interface.NetworkInterface',
      ],
    },
    {
      type: 'category',
      label: 'Engine',
      collapsed: true,
      items: [
        'api/global.tjs.Namespace.engine',
        'api/global.tjs.engine.Variable.compile',
        'api/global.tjs.engine.Variable.serialize',
        'api/global.tjs.engine.Variable.deserialize',
        'api/global.tjs.engine.Variable.evalBytecode',
        'api/global.tjs.engine.Variable.gc',
        'api/global.tjs.engine.Variable.versions',
        'api/global.tjs.TypeAlias.CompiledCode',
      ],
    },
    {
      type: 'category',
      label: 'Utilities',
      collapsed: true,
      items: [
        'api/global.tjs.Function.alert',
        'api/global.tjs.Function.confirm',
        'api/global.tjs.Function.prompt',
        'api/global.tjs.Function.inspect',
        'api/global.tjs.Function.format',
        'api/global.tjs.Function.createConsole',
        'api/global.tjs.Class.Error',
        'api/global.tjs.Interface.ConsolePrinterOptions',
      ],
    },
    {
      type: 'category',
      label: 'Standard Library',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'tjs:assert',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-assert' },
          items: [
            'api/tjs-assert.Variable.Assert',
            'api/tjs-assert.Interface.IAssert',
            'api/tjs-assert.Interface.IAssertionResult',
            'api/tjs-assert.Interface.IAssertOptions',
            'api/tjs-assert.Interface.ComparatorAssertionFunction',
            'api/tjs-assert.Interface.BooleanAssertionFunction',
            'api/tjs-assert.Interface.MessageAssertionFunction',
            'api/tjs-assert.TypeAlias.ErrorAssertionFunction',
          ],
        },
        {
          type: 'category',
          label: 'tjs:ffi',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-ffi' },
          items: [
            'api/tjs-ffi.Class.Lib',
            'api/tjs-ffi.Class.CFunction',
            'api/tjs-ffi.Class.DlSymbol',
            'api/tjs-ffi.Class.Pointer',
            'api/tjs-ffi.Class.PointerType',
            'api/tjs-ffi.Class.StructType',
            'api/tjs-ffi.Class.ArrayType',
            'api/tjs-ffi.Class.AdvancedType',
            'api/tjs-ffi.Class.StaticStringType',
            'api/tjs-ffi.Class.JSCallback',
            'api/tjs-ffi.Interface.SimpleType',
            'api/tjs-ffi.Variable.types',
            'api/tjs-ffi.TypeAlias.PointerAddr',
            'api/tjs-ffi.Function.bufferToString',
            'api/tjs-ffi.Function.stringToBuffer',
            'api/tjs-ffi.Function.errno',
            'api/tjs-ffi.Function.strerror',
          ],
        },
        {
          type: 'category',
          label: 'tjs:getopts',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-getopts' },
          items: [
            'api/tjs-getopts.Function.default',
            'api/tjs-getopts.Interface.Options',
            'api/tjs-getopts.Interface.ParsedOptions',
          ],
        },
        {
          type: 'category',
          label: 'tjs:hashing',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-hashing' },
          items: [
            'api/tjs-hashing.Function.createHash',
            'api/tjs-hashing.Interface.HashObj',
            'api/tjs-hashing.TypeAlias.HashType',
            'api/tjs-hashing.Variable.SUPPORTED_TYPES',
          ],
        },
        {
          type: 'category',
          label: 'tjs:ipaddr',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-ipaddr' },
          items: [
            'api/tjs-ipaddr.Class.IPv4',
            'api/tjs-ipaddr.Class.IPv6',
            'api/tjs-ipaddr.Class.IP',
            'api/tjs-ipaddr.Function.parse',
            'api/tjs-ipaddr.Function.parseCIDR',
            'api/tjs-ipaddr.Function.isValid',
            'api/tjs-ipaddr.Function.process',
            'api/tjs-ipaddr.Function.fromByteArray',
            'api/tjs-ipaddr.Function.subnetMatch',
            'api/tjs-ipaddr.Interface.RangeList',
            'api/tjs-ipaddr.TypeAlias.IPv4Range',
            'api/tjs-ipaddr.TypeAlias.IPv6Range',
            'api/tjs-ipaddr.TypeAlias.IPvXRangeDefaults',
          ],
        },
        {
          type: 'category',
          label: 'tjs:path',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-path' },
          items: [
            'api/tjs-path.Variable.default',
            'api/tjs-path.Variable.posix',
            'api/tjs-path.Variable.win32',
            'api/tjs-path.Interface.IPath',
            'api/tjs-path.Interface.IPathObject',
          ],
        },
        {
          type: 'category',
          label: 'tjs:posix-socket',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-posix-socket' },
          items: [
            'api/tjs-posix-socket.Class.PosixSocket',
          ],
        },
        {
          type: 'category',
          label: 'tjs:sqlite',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-sqlite' },
          items: [
            'api/tjs-sqlite.Class.Database',
            'api/tjs-sqlite.Interface.IDatabaseOptions',
            'api/tjs-sqlite.Interface.IStatement',
            'api/tjs-sqlite.Interface.ITransaction',
          ],
        },
        {
          type: 'category',
          label: 'tjs:uuid',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-uuid' },
          items: [
            'api/tjs-uuid.Variable.v1',
            'api/tjs-uuid.Variable.v3',
            'api/tjs-uuid.Variable.v4',
            'api/tjs-uuid.Variable.v5',
            'api/tjs-uuid.Variable.validate',
            'api/tjs-uuid.Variable.parse',
            'api/tjs-uuid.Variable.stringify',
            'api/tjs-uuid.Variable.version',
            'api/tjs-uuid.Variable.NIL',
          ],
        },
        {
          type: 'category',
          label: 'tjs:wasi',
          collapsed: true,
          link: { type: 'doc', id: 'api/tjs-wasi' },
          items: [
            'api/tjs-wasi.Class.WASI',
            'api/tjs-wasi.Interface.WASIOptions',
            'api/tjs-wasi.TypeAlias.WASIVersion',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
