/*
 * Mozilla CA certificate bundle.
 *
 * The data lives in cacert.c, generated by scripts/update-ca-bundle.sh.
 */

#ifndef TJS_CACERT_H
#define TJS_CACERT_H

#include <stddef.h>

extern const char tjs_cacert_pem[];
extern const size_t tjs_cacert_pem_len;

#endif /* TJS_CACERT_H */
